const express = require("express");
const inventory = express();
const routes = require("./route/auth");
const dishes = require("./route/main");
inventory.use(express.json());
const cors = require("cors");
inventory.use(cors());
inventory.use(routes);
inventory.use(dishes);
inventory.listen(2000);
